<a href="https://colab.research.google.com/github/sudheepelayidom/TrainingSessionsForStudents/blob/main/assignments/Diabates_Dataset_Preproccessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1: Library Import & Dataset Loading**

---

In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
# Load dataset into pandas DataFrame
dataset1 = pd.read_csv("/content/diabetes.csv")
dataset1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76.0,48,180.0,32.9,0.171,63,0
764,2,122,70.0,27,102.5,36.8,0.340,27,0
765,5,121,72.0,23,112.0,26.2,0.245,30,0
766,1,126,60.0,32,169.5,30.1,0.349,47,1
767,1,93,70.0,31,102.5,30.4,0.315,23,0

**2: Target Variable Encoding**

In [ ]:
# Encoding categorical target column
dataset1["Outcome"] = dataset1["Outcome"].apply(lambda e: 0 if e == "N" else 1)
dataset1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,1
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,1
4,0,137,40.0,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76.0,48,180.0,32.9,0.171,63,1
764,2,122,70.0,27,102.5,36.8,0.340,27,1
765,5,121,72.0,23,112.0,26.2,0.245,30,1
766,1,126,60.0,32,169.5,30.1,0.349,47,1
767,1,93,70.0,31,102.5,30.4,0.315,23,1

 **3: Duplicate Row Detection and Removal**

In [ ]:
# Check for duplicates across all columns
dataset1.duplicated()
# Remove duplicate rows directly in memory
dataset1.drop_duplicates(inplace=True)
dataset1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,1
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,1
4,0,137,40.0,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76.0,48,180.0,32.9,0.171,63,1
764,2,122,70.0,27,102.5,36.8,0.340,27,1
765,5,121,72.0,23,112.0,26.2,0.245,30,1
766,1,126,60.0,32,169.5,30.1,0.349,47,1
767,1,93,70.0,31,102.5,30.4,0.315,23,1

**4: Handle Missing Values**

In [ ]:
# BLOCK 4: FILL IN THE BLANKS (IMPUTATION)
from sklearn.impute import SimpleImputer

# 1. Fill missing 'Age' data using the Average (Mean Strategy)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
dataset1["Age"] = imputer.fit_transform(dataset1["Age"].values.reshape(-1, 1))

# 2. Fill missing 'Pregnancies' data using the Most Frequent number (Mode Strategy)
# We use mode here because you can't have 2.5 pregnancies! It must be a whole number.
imputer_mode = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
dataset1["Pregnancies"] = imputer_mode.fit_transform(dataset1["Pregnancies"].values.reshape(-1, 1))

print("Block 4 Complete: Missing values in 'Age' and 'Pregnancies' have been filled using statistics!")

Block 4 Complete: Missing values in 'Age' and 'Pregnancies' have been filled using statistics!

**5: Outlier Detection and Filtering (IQR Method)**

In [ ]:
# BLOCK 5: DETECT AND REMOVE EXTREME OUTLIERS
# 1. Separate our 'Answers' (Outcome) from our 'Questions' (All other columns)
X = dataset1.drop(columns=['Outcome'])
y = dataset1['Outcome']

# 2. Calculate the statistical boundaries (Quartiles)
Q1 = X.quantile(0.25) # The 25% mark
Q3 = X.quantile(0.75) # The 75% mark
IQR = Q3 - Q1         # The distance between them

# 3. Create a rule to keep only the rows within normal, safe bounds
normal_mask = ~((X < (Q1 - 1.5 * IQR)) | (X > (Q3 + 1.5 * IQR))).any(axis=1)

# 4. Apply the rule to create our clean dataset
X_clean = X[normal_mask].copy()
y_clean = y[normal_mask].copy()

print(f"Block 5 Complete: Outliers removed!")
print(f"We safely threw away {X.shape[0] - X_clean.shape[0]} rows containing extreme mistakes.")

Block 5 Complete: Outliers removed!
We safely threw away 178 rows containing extreme mistakes.

**6: TRAIN / TEST SPLIT**

In [ ]:

from sklearn.model_selection import train_test_split

# Split the data: 80% for learning (Train), 20% for testing (Test)
# random_state=42 ensures every student gets the exact same random shuffle
X_train, X_test, y_train, y_test = train_test_split(
    X_clean, y_clean, test_size=0.20, random_state=42, stratify=y_clean
)

print("Block 6 Complete: Data successfully split!")
print(f"The AI will learn from {X_train.shape[0]} patients (Training Set).")
print(f"The AI will be tested on {X_test.shape[0]} hidden patients (Testing Set).")

Block 6 Complete: Data successfully split!
The AI will learn from 472 patients (Training Set).
The AI will be tested on 118 hidden patients (Testing Set).

**7: Feature Scaling (Standardization)**

In [ ]:
#  NORMALIZE THE NUMBERS (SCALING)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# FIT (learn the math) and TRANSFORM (apply it) strictly on the Training Set
X_train_scaled = scaler.fit_transform(X_train)

# ONLY TRANSFORM the Test Set (Never 'fit' on the test set to prevent cheating!)
X_test_scaled = scaler.transform(X_test)

# Convert the results back into readable Pandas DataFrames
X_train_final = pd.DataFrame(X_train_scaled, columns=X_clean.columns)
X_test_final = pd.DataFrame(X_test_scaled, columns=X_clean.columns)

print("Block 7 Complete: All features are now scaled to a uniform range!")
display(X_train_final.head(3))

Block 7 Complete: All features are now scaled to a uniform range!

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.336086,-0.144217,0.340273,0.536316,1.022921,-0.125459,-0.345843,1.032665
1,0.641737,-0.950409,1.848780,-0.278166,-0.488708,-1.941829,-0.954018,-0.424488
2,-0.580866,-1.686497,-0.225417,-0.278166,-0.488708,-0.639830,0.607618,-0.970921

**8:Download the Preprocessed Dataset**

In [ ]:
# STITCH TOGETHER AND DOWNLOAD
from google.colab import files

# Reset the indexes so the features and target align perfectly
X_train_final.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

# Combine the clean features (X) and the clean answers (y) into one final table
final_clean_dataset = pd.concat([X_train_final, y_train], axis=1)

print("  Here is your final, machine-learning-ready dataset: ")
display(final_clean_dataset.head(5))

# Save to a CSV file
final_clean_dataset.to_csv("FINAL_preprocessed_diabetes_data.csv", index=False)

# Trigger the download
files.download("FINAL_preprocessed_diabetes_data.csv")
print("\nDownloading 'FINAL_preprocessed_diabetes_data.csv' to your computer...")

 PIPELINE COMPLETE! Here is your final, machine-learning-ready dataset:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.336086,-0.144217,0.340273,0.536316,1.022921,-0.125459,-0.345843,1.032665,1
1,0.641737,-0.950409,1.848780,-0.278166,-0.488708,-1.941829,-0.954018,-0.424488,1
2,-0.580866,-1.686497,-0.225417,-0.278166,-0.488708,-0.639830,0.607618,-0.970921,1
3,0.336086,0.977441,0.245991,-0.278166,-0.488708,-0.334422,0.011214,-0.424488,1
4,0.030436,-1.195772,-1.356797,-1.092649,-1.695755,-0.671978,-0.491021,-0.424488,1

Downloading 'FINAL_preprocessed_diabetes_data.csv' to your computer...